---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 3.7.3
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 3.7.3
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Fixed name suffix for HTTPRoute
    - kind: fixed
      description: |-
        Fixed incorrect default backendRefs values in HTTPRoute
